require("user.options")
require("user.plugins")
require("user.keymaps")
--require("user.colorscheme")
require("user.cmp")
--require("user.lsp")
require("user.telescope")
require("user.statusline")
require("user.symbol_outline")
require("user.bufferline")
require("user.treesitter")
require("user.autopairs")
require("user.nvim-tree")
require("user.gitsigns")
require("user.terminal")
require("user.rust")

require('onedark').setup()
